# Generated by Django 6.0.2 on 2026-02-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='review',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
