# Generated by Django 6.0.2 on 2026-02-14 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='room',
            name='room_room_price_p_776487_idx',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='price_per_night',
            new_name='base_price_per_night',
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='services',
            field=models.JSONField(default=list, help_text='List of services: air_conditioning, wifi, tv, minibar, etc'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['base_price_per_night'], name='room_room_base_pr_db3a75_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active'], name='room_room_is_acti_de728b_idx'),
        ),
    ]
