# Generated by Django 6.0.2 on 2026-02-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('room', '0003_pricingrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(choices=[('maintenance', 'Maintenance'), ('personal_use', 'Personal Use'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availabilities', to='accounts.staff')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='room.room')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'start_date', 'end_date'], name='room_roomav_room_id_c4b383_idx')],
            },
        ),
    ]
