# Generated by Django 5.2.11 on 2026-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('EMAIL', 'Email')], max_length=20),
        ),
    ]
