# Generated by Django 6.0.2 on 2026-02-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='guest',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
