# Generated by Django 6.0.2 on 2026-02-14 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('services', models.CharField(blank=True, help_text='Comma-separated services', max_length=255)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_rooms', to='accounts.manager')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='room.room')),
            ],
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['location'], name='room_room_locatio_94d7ae_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['price_per_night'], name='room_room_price_p_776487_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['capacity'], name='room_room_capacit_220017_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['average_rating'], name='room_room_average_d90efa_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['manager'], name='room_room_manager_2b3c33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomimage',
            unique_together={('room', 'is_main')},
        ),
    ]
