# Generated by Django 6.0.2 on 2026-02-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_room_room_room_price_p_776487_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('weekend', 'Weekend'), ('holiday', 'Holiday'), ('seasonal', 'Seasonal'), ('length_of_stay', 'Length of Stay')], max_length=20)),
                ('price_modifier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_percentage', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('min_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('days_of_week', models.JSONField(default=list, help_text='List of day numbers, e.g., [5,6] for Fri-Sat')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='room.room')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'is_active'], name='room_pricin_room_id_0932e0_idx'), models.Index(fields=['priority'], name='room_pricin_priorit_3aa5b9_idx')],
            },
        ),
    ]
