# Generated by Django 5.2.11 on 2026-02-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_pricingrule_deleted_pricingrule_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
