# Generated by Django 5.2.11 on 2026-04-01 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_alter_pricingrule_id_alter_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geographic latitude (-90 to 90)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geographic longitude (-180 to 180)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
