# Generated by Django 5.2.11 on 2026-02-27 17:27

import api.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='guest',
            managers=[
                ('objects', api.accounts.models.GuestManager()),
            ],
        ),
    ]
