# Generated by Django 5.2.11 on 2026-03-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_guest_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='source',
            field=models.CharField(choices=[('self_registered', 'Self Registered'), ('staff_created', 'Staff Created')], default='staff_created', editable=False, help_text='Source of guest creation (self-registered or staff-created)', max_length=20),
        ),
    ]
