# Generated by Django 5.2.11 on 2026-03-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_guest_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account ID (acct_xxx)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='stripe_connect_charges_enabled',
            field=models.BooleanField(default=False, help_text='Whether the account can accept charges'),
        ),
        migrations.AddField(
            model_name='manager',
            name='stripe_connect_onboarding_complete',
            field=models.BooleanField(default=False, help_text='Whether Stripe Connect onboarding is complete'),
        ),
        migrations.AddField(
            model_name='manager',
            name='stripe_connect_payouts_enabled',
            field=models.BooleanField(default=False, help_text='Whether the account can receive payouts'),
        ),
    ]
